unikubehq/cli

src/cli/orga.py
src/cli/package.py

feat(context): package use added

---

src/cli/project.py

fix(#27): project down

---

.github/workflows/python-app.yaml

Test setup suggestion for #38 .

chore: add pytest to workflow

---

src/cli/app.py
src/cli/project.py

Alias for shell command #15 .
I used `ctx.forward()`, since an approach as presented in https://stackoverflow.com/questions/46641928/python-click-multiple-command-names did not work.

exec alias

---

src/cli/deck.py

Unikube deck install without preceding project up raises Error

---

src/cli/deck.py
src/cli/orga.py
src/cli/project.py
src/helpers.py

ID as selection parameter + map organization/project/deck/app arguments to ID

---

src/cli/console/exit.py
src/cli/deck.py
src/helpers.py
tests/test_cli_helper.py
tests/test_cli_orga.py

Refreshing token for fetching manifests

---

.pre-commit-config.yaml
src/cli/deck.py
tests/test_cli_deck.py
unikube.py

I also added a default language version for the pre-commit config. That fixed my issues with the isort hook.

Cli 54: add `deck ingress` command

---

src/cli/auth.py
src/cli/system.py
src/helpers.py
tests/test_cli_auth.py

PR for the issue #58 
Implements for `login` and `system verify`.

Info about availability of the newer version

---

src/cli/project.py
src/helpers.py

Project organization option

---

src/cli/deck.py

Inconsistent deck exceptions

---

src/cli/project.py

Fixes errors produced by merge.

fix: missing imports from helpers

---

src/cli/app.py

feature: adds app info and env command implementation

---

requirements.txt
setup.py
src/cli/console/input.py

refactor: replace inquirer with InquirerPy

---

README.md

Add installation description via `pip` and `brew`.

chore: add installation description to README.md

---

docs/development.rst
src/cli/app.py
src/local/system.py
src/unikubefile/unikube_file_1_0.py

docs: adds documentation for port settings

feat: adds port setting in unikubefile

---

src/cli/app.py

fix: exclude pods which are not in an acceptable phase

---

src/cli/app.py

feat: check if port request in switch operation is actually free

---

src/cli/app.py
src/local/system.py
src/settings.py

feature: add service tokens to switched container

---

src/cli/app.py
src/cli/console/input.py
src/local/system.py

Also add to `app update` command.
Closes #200

feat: add multiselect capability to console.list

---

src/cli/console/input.py

fix: add space as toggle for fuzzy multiselect

---

setup.py

refactor: change entry_points syntax

---

src/cli/app.py
src/cli/console/__init__.py
src/cli/console/container.py
src/local/system.py

feat(#230): app shell container flag

---

src/cli/context.py
src/context/context.py
src/unikubefile/selector.py
src/unikubefile/unikube_file.py
src/unikubefile/unikube_file_1_0.py

Closes #161 ? Test with new dev release.

fix(#161): unikube file context

---

src/cli/deck.py

fix(#179): abort deck install when app is switched

---

src/cli/console/helpers.py
src/cli/context.py
src/cli/project.py
src/cli/unikube.py
src/context/context.py

fix(#164): show context names/titles

---

src/cli/utils.py

chore: spinner 

---

src/cli/app.py
src/cli/helper.py

Displays age of a pod in `app list` command.

feature: add age to app list

---

setup.py

fix(#282): add missing dependency

---

unikube/local/providers/k3d/k3d.py

fix(k3d): proper handling of unsuccessful cluster start

---

MANIFEST.in

fix(#291): fix missing files

---

requirements.txt

fix: pin kubernetes < 22.0.0

---

tests/test_cli_init.py
unikube/cli/console/__init__.py
unikube/cli/console/input.py
unikube/cli/init.py
unikube/commands.py
unikube/settings.py

unikube init command

---

unikube/graphql_utils.py

Exception type changed in python gql. After bumping the package a generic
error message was displayed when the user was not authenticated.
Fixes #306

fix(#306): generic exit error when not authenticated
